### ISSUE TITLE
Does it work with the new template-level subscriptions?

### ISSUE THREAD

**Issue by funkybunky** [ccorcos/meteor-subs-cache#1]
this question is related to this thread on the forums: https://forums.meteor.com/t/template-subscribe-and-subsmanager/2003

**Comment by ccorcos** [comment]
yeah, just wrap it in an autorun

```coffee
Template.something.onCreated ->
  @autorun ->
    subsCache.subscribe( ... )
```

**Comment by funkybunky** [comment]
Thank you very much!
And thank you for the package itself!
