### ISSUE TITLE
There is no such publish handler named: undefined

### ISSUE THREAD

**Issue by elie222** [ccorcos/meteor-subs-cache#16]
I just switched over from subsManager, and this is the error message I'm seeing on the server:
`There is no such publish handler named: undefined`

Was working fine before the switch over. Any ideas?

**Comment by ccorcos** [comment]
This isn't exactly compatible with subs manager

**Comment by elie222** [comment]
The only method I use from subsmanager is subscribe. And in general it all
works well when switching over. But I see that error message on the server

**Comment by paranoico** [comment]
Closing since it seems not directly related as @ccorcos pointed out.
