### ISSUE TITLE
Use in mobile apps, with throteling network

### ISSUE THREAD

**Issue by joaopiopedreira** [ccorcos/meteor-subs-cache#2]
Hi @ccorcos, I'm thinking of using your package in a mobile app (meteor-cordova app), already in pre-production.

I had 2 main problems to solve in this app:
- Treat static, potentially big collections outside of meteor livedata package (no pub/sub): got this with the [DumbCollections](https://github.com/richsilv/meteor-dumb-collections) package;
- Try to reuse subscriptions between offline/online transitions, even when the browser refreshes. This is to avoid the overhead caused by reloading all data associated to subscribed collections on an offline/online transition (my users may be in zones with a poor network coverage, experiencing many reloads in a short intervals of time) 

This last issue is giving me some work. It's a hard problem to solve. I though I could hold on to the subscription handle, save it in local storage and then find a way to reuse it like this: 

    //subsHandle holds the subs object before refresh
    // after refresh, I could hold on to it like:
    subsHandle = Meteor.subscribe(...)

But it's not that simple. Do you think there's a way to achieve this?

Thanks

**Comment by ccorcos** [comment]
Hmm this package does something slightly different than what you're looking for. I'm not sure it's possible though. Here's why. 

Merge box keeps track of all subscriptions and all the data on the client so it can send a minimal amount of data to the client. When the connection terminates, the server forgets all the pub/sub information. 

You could save the data in local storage but I don't know how you'd restart the subscription.
