### ISSUE TITLE
Subscriptions are stopped prematurely when the cache overflows

### ISSUE THREAD

**Issue by BudgieInWA** [ccorcos/meteor-subs-cache#22]
When the cache overflows SubsCache doesn't only stop subscriptions that have been held back, but may stop subscriptions that have not been stopped at all. It should instead only stop subscriptions that have had `stop` called on them, but have not yet actually been stopped because of the caching.

The current behaviour is surprising and does not conform the the documented behaviour: "`cacheLimit` is the max number of subscriptions to cache".

**Comment by paranoico** [comment]
Based on recent revision, in first place when cache overflow, Meteor application restarts, breaking all connections and sometimes reverting app to an old version.
It seems to Worker Service is a much better approach than cache.
So I do not think it could be possible to not stop subscriptions before of application crash.
