### ISSUE TITLE
Reasons for deprecation?

### ISSUE THREAD

**Issue by gaurav-** [ccorcos/meteor-subs-cache#24]
Hi @ccorcos,

We only recently started using this package, to replace SubsManager that's causing us some problems.  But I just found out about the deprecation notice you added a few days ago. Could you share the reasons – is it because you don't plan to maintain it anymore or are there some serious issues with the approach of taken by this library?

Thanks.

**Comment by ccorcos** [comment]
Library works. Just I maintained. I haven't used meteor in over a year now.
And I think they way tracker works is a bad idea. I would recommend
Featherjs as an alternative

**Comment by ccorcos** [comment]
Unmaintained*

**Comment by gaurav-** [comment]
Got it. Thanks for the clarification!

**Comment by gaurav-** [comment]
Just curious, if you have used the other FRP libraries out there and if you found any of them to be a "better version" of Tracker?

**Comment by ccorcos** [comment]
Flyd is awesome. But I would shy away from using streams -- they're easy to
overuse. Check out the Elm Architecture Tutorial
