### ISSUE TITLE
Why is the package deprecated now?

### ISSUE THREAD

**Issue by afuggini** [ccorcos/meteor-subs-cache#27]

**Comment by snajjar** [comment]
+1. 

Why? I'm using it because it does provide more ganularity compared to https://github.com/kadirahq/subs-manager

**Comment by ccorcos** [comment]
Because I keep getting issue tickets and PRs that I literally cannot review anymore. I havent used Meteor in over a year. I suppose I should change that to "NEEDS MAINTAINERS"

**Comment by snajjar** [comment]
I think this is worth opening a thread on the meteor forums. You are quite a great community member and you provided quality packages, it would be a shame to let it be dropped overtime.

**Comment by afuggini** [comment]
+1

**Comment by ccorcos** [comment]
That's a fair point... I'll do that.

**Comment by afuggini** [comment]
That'd be cool.

**Comment by ccorcos** [comment]
https://forums.meteor.com/t/maintainers-needed/30762
