### ISSUE TITLE
Code conversion to JavaScript

### ISSUE THREAD

**Issue by paranoico** [ccorcos/meteor-subs-cache#28]
Hello,

Is there any chance to convert code to JavaScript?

In that case, we can maintain it at my company. We use your component in one of our biggest project, so we will have it up and running for quite long time. Must say that we do not use CoffeScript at all.

Let me know what you think.

And thanks a lot for your amazing job.

**Comment by ccorcos** [comment]
You are more than welcome to convert it to JS -- shouldnt be too hard.

**Comment by paranoico** [comment]
Thanks a lot, let me then try to understand it first. Regards.

**Comment by Fen747** [comment]
Hi,

I'd too liked to convert this project to javascript, and propose to help maintaining the repo alive.

**Comment by paranoico** [comment]
Great @Fen747, thanks.

And @ccorcos, I think the best thing is first merge those pending Push Requests. Then I can try to convert it to JS.

What do you think? We have tested some of those PRs and think I can safely merge them.

**Comment by ccorcos** [comment]
What we need to do is: (1) figure out how to give you guys publishing access to publish to the meteor packaging system and (2) I'll give you guys access to the repo so you can merge them yourselves :)

**Comment by paranoico** [comment]
Precisely,  yes of course we need access, we can do the merge. And everything else.
You can set up us as collaborators to the project or some other permissions as team members.
But I am afraid that only you can do it.

**Comment by ccorcos** [comment]
@paranoico added you as a collaborator

**Comment by paranoico** [comment]
Thanks @ccorcos, will start to check it.

**Comment by paranoico** [comment]
Hello @ccorcos, I have done 2 PRs and now it is necessary to update Meteor Package, ¿can I do it also? ¿Or how do we proceed?

**Comment by ccorcos** [comment]
I need to figure out how to add permissions for you to publish -- I
couldn't find it on meteor.com. Any ideas?

**Comment by paranoico** [comment]
@ccorcos I think this could help:
http://stackoverflow.com/questions/29267399/how-to-add-collaborator-for-meteor-package-in-atmosphere

**Comment by ccorcos** [comment]
```
~ ❯❯❯ meteor admin maintainers ccorcos:subs-cache --add paranoico
Please log in with your Meteor developer account. If you don't have one, you
can quickly create one at www.meteor.com.
Username: ccorcos
Password:
Adding a maintainer to ccorcos:subs-cache...

The maintainers for ccorcos:subs-cache are:
ccorcos
paranoico
```

all yours :)

**Comment by ramijarrar** [comment]
Hi @paranoica - as heavy users of this package, we are very happy to hear there is a new maintainer.

Would it be possible to remove the warning in the README now (so as to avoid discouraging other users)?

**Comment by paranoico** [comment]
Hello @ramijarrar , it is done. Thanks.

**Comment by scottburch** [comment]
Maybe atmosphere is not the best way to maintain it since Meteor is moving away from their packages and toward NPMs.  I needed this to use this with connections so I ran the code through decaffeinate made the quick change and added to my common-lib npm module for my projects.  So, proof it is possible.

**Comment by ramezrafla** [comment]
@paranoico , we went ahead and converted to vanilla JS. Interested in a PR?

**Comment by Fen747** [comment]
@ramezrafla Could you please release the code in your own repo ? It doesn't seems that this one is going to revive anytime soon, and I'm interested in having a full JS version of this package. Thanks you.

**Comment by paranoico** [comment]
Hello @ramezrafla , I think I cannot add maintainers, I am not the owner.

But please make a Push Request.

And sorry, we have not had time enough to follow project in weeks. I just merged several PRs a month ago and released new package to Atmosphere. @Fen747 is not informed properly.

**Comment by paranoico** [comment]
@ramezrafla How about if I create a new branch for your PR? In order to test conversion properly before uploading to Atmosphere.

**Comment by ramezrafla** [comment]
@paranoico, please do. Thanks!

**Comment by paranoico** [comment]
@ramezrafla Ready, new branch is named JS-Migration, there I am going to merge your PR.

**Comment by tcastelli** [comment]
Good to know it is now maintained again :). I am also willing to help if the code gets converted to JS too.

On a side note, I was using the fork from @ElvishJerricco since it was more updated, and now that I see this is becoming the main one, I have noticed there are some commits in the fork that are not present in this repo.
Maybe it would help to copy those changes in this repo too? (If it's not possible to get PRs from the author).

Some important examples
- https://github.com/ElvishJerricco/meteor-subs-cache/commit/03c38ad4701f8ef67e13ab38c9eb165927293e45
- https://github.com/ElvishJerricco/meteor-subs-cache/commit/e310ce59c70d5dd6655c7048b18ce96c92d468e4
- https://github.com/ElvishJerricco/meteor-subs-cache/commit/bd05cde611cccb0994b13f7200b9dde58e616017

**Comment by ramezrafla** [comment]
Thanks! I'll start preparing the package to PR. Give me a couple of days, as right now, we extracted the main js out of the package and directly embedded in our app.

**Comment by paranoico** [comment]
Thanks @tcastelli ,
We are going to check ElvisJerrico changes, In matter of fact we already saw that he had several additional changes but wanted to saty with Ccorcos version since there was a specific functionality we needed.

**Comment by paranoico** [comment]
Thanks to you @ramezrafla ,
Take your time, I think it will be in a week or two when we can make our first try to translate to JS.

**Comment by ramezrafla** [comment]
Thanks @paranoico, we already translated to JS and using in production. Between today and tomorrow we should have PR ready

**Comment by afruth** [comment]
@ramezrafla what's the status for the code conversion? :)

**Comment by ramezrafla** [comment]
Really sorry --- too much work :)
It's already converted, just need to test it as a package (right now we embedded directly into our app).

Today, pinky promise!

**Comment by ramezrafla** [comment]
PR #34 submitted - please look at the notes. Testing of package.js needed (sorry, no time and I didn't want to keep holding others back)

**Comment by lmachens** [comment]
The atmoshphere package is not updated yet right?
https://atmospherejs.com/ccorcos/subs-cache

It published the old coffeescript package.

**Comment by paranoico** [comment]
@lmachens that is correct, atmosphere package has not been updated yet, since we have not finished testing of new JS code. I do not want to break the working Coffeescript until we are sure the new one works well. Until we test it on field operations and have no issues I will be willing to update atmosphere.

Have you tested JS code already on your application?

**Comment by lmachens** [comment]
No, but I had problems to set up this package.
Readme.md:
`meteor add ccorcos:subs-cache`

`subsCache = new SubsCache(5, 10);`

This will not work until you update the atmosphere package. 
The constructor in the coffeescript packae is different:
`subsCache = new SubsCache({ expireAfter: 5, cacheLimit:10});`

**Comment by paranoico** [comment]
You are right, there are differences, Readme was updated when master branch was updated.

We are trying to release new version on 20 mobile devices to test it on field on 2 weeks.

**Comment by paranoico** [comment]
Today Atmosphere package has been updated with last version. Thanks all for your help and patience.
