### ISSUE TITLE
Doesn't seem to work for subscription params?

### ISSUE THREAD

**Issue by satyavh** [ccorcos/meteor-subs-cache#3]
Hi, great package. But it seems it can't handle subscription params? Because when I do something like this:

`SubsCache.subscribe 'singlePost', id`

it will return the same subscription from cache even when `id` changes.

**Comment by ccorcos** [comment]
hmm. that shouldn't be an issue. I'm using the params as a key.

https://github.com/ccorcos/meteor-subs-cache/blob/master/src/subsCache.coffee#L54

**Comment by ccorcos** [comment]
Can you please submit a meteorpad example? Else I'm closing this issue...
