### ISSUE TITLE
Mongo is not defined

### ISSUE THREAD

**Issue by dnish** [ccorcos/meteor-subs-cache#31]
After adding the package to my project, the server crashes with the following error:

```
W20161215-20:21:24.603(1)? (STDERR) ReferenceError: Mongo is not defined
W20161215-20:21:24.603(1)? (STDERR)     at packages/ccorcos_subs-cache.js:288:18
W20161215-20:21:24.603(1)? (STDERR)     at packages/ccorcos_subs-cache.js:292:4
W20161215-20:21:24.603(1)? (STDERR)     at packages/ccorcos_subs-cache.js:351:3
```

**Comment by paranoico** [comment]
@dnish Confirming this is a bug on new version, working on fixing.

**Comment by paranoico** [comment]
@dnish After trying to catch error, it seems to be related to Coffeescript, and nobody here could fix it.
So I have removed examples folder (am going to create a sample in a separate project outside from subs-cache) and new version on Atmosphere is now working correctly.
At least, we are sure that the error only raised on Atmosphere version, not when using local package code.

Please check it out, I am going to close the issue for now. I will reopen if it persists.
Let me now if you find something else. Thanks a lot.
