### ISSUE TITLE
sub.onReady() not working

### ISSUE THREAD

**Issue by muninn9** [ccorcos/meteor-subs-cache#33]
This is not working, nothing shows up in the console when the onReady callback should be called. Suggestions?

```
const subs = new SubsCache({expireAter: 5, cacheLimit: 5});
const sub = subs.subscribe("videos", params);

sub.onReady(function() {
    console.log('hello');
}
```

**Comment by paranoico** [comment]
Hello @muninn9 ,

Not sure about your code, but the standard callback works:
```
subs.subscribe('videos, params, {
          onReady: () => {
.....
}});
```

Or, something like this (we use it in a React container), where Videos is the JS collection:

```
subs.subscribe('videos', params);

if (Videos.isReady()) {
....
}
```

**Comment by ramezrafla** [comment]
or just pass the function as your last argument.
