### ISSUE TITLE
No way this can work

### ISSUE THREAD

**Issue by gregory** [ccorcos/meteor-subs-cache#38]
The version in this package is [0.9.0](https://github.com/ccorcos/meteor-subs-cache/commit/7fd20c2debe4d84d0e7e0f2863cc8e99557cdf51#diff-49fb32b6d8276ecd1268e47c0339d55cR4) but has never been published to atmospher 

![screenshot 2017-07-06 10 57 33](https://user-images.githubusercontent.com/167488/27925542-fc9dfffe-6239-11e7-98c0-dc6d2b0b53b3.png)

Also, there package is trying to load [src/subsCache.js](https://github.com/ccorcos/meteor-subs-cache/blob/master/package.js#L19) but the filename is src/**S**ubsCache.js

That plus the fact it's written in es5 and the package doesn't include `ecmascript`
I opened a PR #37 to fix it.

**Comment by paranoico** [comment]
@gregory You are correct, atmosphere package is NOT updated, since component has been changed from Coffeescript to Javascript and we have not finished testing all functionality we use yet.

Will review pending testing as soon as as can, thanks for the PR.

**Comment by jankapunkt** [comment]
@paranoico do you really have the time to maintain this repo? Seems not to be that big but this issue still remains!?

**Comment by paranoico** [comment]
@jankapunkt Sorry, I have not time yet.

Coffescript version is still working correctly and published. We cannot release JS version yet to our mobile devices. There is a problem regarding offline data gathering and then restarting device, but do not know if we have to modify this component yet.

**Comment by jankapunkt** [comment]
Ok, seems understandable. Is there a reason, why you can't add the tests to this repo? Maybe we can provide some support in testing and find the error.

**Comment by paranoico** [comment]
Well, again our time in my side is the main reason. Currently we use also ground-db and cordova-plugin-kiosk among other plugins.
So I am pretty sure the error is gound and efforts here are in that directions, I will try to add some tests as u suggest next week.
If you can provide those PR via, it will be very welcome also.

**Comment by jankapunkt** [comment]
I can provide some tests but I only some unit tests in mocha. Would that be an improvement?

**Comment by jankapunkt** [comment]
I already wrote some unit tests with mocha and found some inconsistencies in a helper function. I will open a PR once I have completed tests for the all functions in the api.

Maybe I find some more things to fix which may also help you with your mobile issue

**Comment by jankapunkt** [comment]
please see #39

**Comment by paranoico** [comment]
Both PRs are merged now, my team and I will start testing next week on my side.

Sorry about my month and a half delay.

**Comment by paranoico** [comment]
@jankapunkt  The file **src/SubsCache.js** does not exists in current master branch, it seems you changed its name on your PR to src/**s**ubsCache.js back again. Am I right?

**Comment by jankapunkt** [comment]
Yes I changed the Filename to way, how it has been referenced in the package.js File.

**Comment by jankapunkt** [comment]
I can fix that and open a new PR, please let me know, which naming you do prefer.

**Comment by jankapunkt** [comment]
Please see #40

**Comment by paranoico** [comment]
Good @jankapunkt , thanks, and I agree file should be named **S**ubsCache since that was the initial name @ramezrafla used on his first JS version commit months ago.
