### ISSUE TITLE
Error: Can't set timers inside simulations

### ISSUE THREAD

**Issue by maxnowack** [ccorcos/meteor-subs-cache#4]
Callstack:
````
Error: Can't set timers inside simulations
    at withoutInvocation (timers.js:5)
    at bindAndCatch (timers.js:13)
    at Object._.extend.setTimeout (timers.js:29)
    at Object.SubsCache.SubsCache.subscribeFor.cachedSub.delayedStop (subsCache.coffee:89)
    at subsCache.coffee:85
    at tracker.js:263
    at Object.Tracker.nonreactive (tracker.js:560)
    at Tracker.Computation.invalidate (tracker.js:262)
    at Tracker.Computation.stop (tracker.js:279)
    at null.<anonymous> (view.js:203)
````

**Comment by ccorcos** [comment]
Can I get some context? "inside simulation" makes me think something is happening in a Meteor.method...

**Comment by maxnowack** [comment]
I start the subscription in a `Template.onCreated()` (inside `this.autorun()`) function, to get cached template level subscriptions. If the data for the template instance get removed, the template will be destroyed. The error occurs on destroying the template

**Comment by ccorcos** [comment]
https://github.com/meteor/meteor/blob/release/METEOR%401.1.0.2-diagnose-netstat-error-2/packages/meteor/timers.js#L4

https://github.com/meteor/meteor/blob/release/METEOR%401.1.0.2-diagnose-netstat-error-2/packages/ddp/livedata_common.js#L170

https://github.com/meteor/meteor/blob/release/METEOR%401.1.0.2-diagnose-netstat-error-2/packages/meteor/dynamics_browser.js#L6

I tried chasing it around. Getting pretty lost here. Would you mind sending me some more code or setting up a minimal MeteorPad?

**Comment by maxnowack** [comment]
Here's a MeteorPad: http://meteorpad.com/pad/MwuA7rasNrd2SGpxN/Leaderboard
I hope it's okay for you that I used coffeescript.

The error occurs if you click the "x" to remove a player

**Comment by ccorcos** [comment]
Hmm. I've never used Template.currentData() but I think thats the issue.

This works:

http://meteorpad.com/pad/FvHmens47jwYLrgrN/Copy%20of%20ccorcos:subs-cache#4
