### ISSUE TITLE
Atmosphere update?

### ISSUE THREAD

**Issue by nicooprat** [ccorcos/meteor-subs-cache#42]
Looks like the package hasn't been published on Atmosphere for a while, is it on purpose?

https://atmospherejs.com/ccorcos/subs-cache

**Comment by paranoico** [comment]
Yes, you are right, it is on purpose, you can see #28.
Now we are almost ready to update it in following days.

**Comment by paranoico** [comment]
Today Atmosphere package has been updated with last version.
