### ISSUE TITLE
Multiple subscription with same name

### ISSUE THREAD

**Issue by lmachens** [ccorcos/meteor-subs-cache#44]
Hey,
I have a problem with the recent version of this package.
The problem is, that subs-cache updates the subscription if a paramter changes (except first param).
If I have two subscriptions on the same page, the last called subsribe will update the first one.

```
SubsCache.subscribe('user', id1);
SubsCache.subscribe('user', id2);
```

In the older versions of this package, multiple cached subscriptions were possible.
I think it is related to the hash calculation (you only use the first param for it).

**Comment by paranoico** [comment]
PR merged, thanks @lmachens
