### ISSUE TITLE
Using with fast render within flow-router breaks

### ISSUE THREAD

**Issue by janat08** [ccorcos/meteor-subs-cache#47]
I tried several ways to pass subsmanager.subscribe to this.register, and it broke.

```
var subs = new SubsCache(5, 15)
var subscribe = subs.subscribe
FlowRouter.route('/', {
  name: 'BLOCKRAZOR',
  subscriptions: function () {
    this.register('approvedcurrencies',subscribe("approvedCurrencies");
  },
  action() {
    BlazeLayout.render('desktop', {
      main: 'returnedCurrencies',
      left: 'menu'
    });
  }
})
```
Passing invoking subs.subscribe within this.register also broke.
this is the error message on client with fast render reporting same issue on server:
```
TypeError: Cannot read property 'apply' of undefined
    at SubsCache.subscribe (SubsCache.js:85)
    at Route.subscriptions [as _subscriptions] (routes.js:57)
    at Route.callSubscriptions (staringatlights_flow-router.js?hash=54561903308af27a237544b4c13ed49f3776b07e:896)
    at staringatlights_flow-router.js?hash=54561903308af27a237544b4c13ed49f3776b07e:597
    at Tracker.Computation._compute (tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:339)
    at Tracker.Computation._recompute (tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:358)
    at Object.Tracker._runFlush (tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:532)
    at Object.Tracker.flush (tracker.js?hash=997515fa2d5b0530ba07741da556c4b36963ef3b:483)
    at Router._invalidateTracker (staringatlights_flow-router.js?hash=54561903308af27a237544b4c13ed49f3776b07e:659)
    at afterAllTriggersRan (staringatlights_flow-router.js?hash=54561903308af27a237544b4c13ed49f3776b07e:271)
```

**Comment by paranoico** [comment]
@janat08 It seems we missed some code for fast render when converted to Javascript, there was code merged from @BudgieInWA in 2015 that take cares of it as you can see en #8 or directly in the file in [Coffee June 2015 Version](https://github.com/BudgieInWA/meteor-subs-cache/blob/7fe886145f572cec618926cb24a54eb29c6a0d46/src/subsCache.coffee#L84)

Specifically the following lines was not converted to JS in new version:
```
subscribeFor: (expireTime, args...) ->
    if Meteor.isServer
      # If we're using fast-render for SSR
      Meteor.subscribe.apply(Meteor.args)
    else
```
I think it is the origin of your issue.

@ramezrafla What do you think? Does it was removed on purpose for any reason when you converted it to JS?

**Comment by ramezrafla** [comment]
We only use SubsCache client-side, so didn't need that.

**Comment by paranoico** [comment]
OK thanks.

@janat08 We have a pending change for next week to update Atmosphere, if you can wait a bit more, we can make the change for you. Or feel free to post a PR if you can contribute with this detail.

Other option is that you use the older version of the component in Coffee Script.

**Comment by janat08** [comment]
I suppose there's no integration with flow-router's fast render so that it doesn't fast-render stuff which is already cached?

**Comment by paranoico** [comment]
Well, as far as I can see, the missing code previously posted is meant to work only on Server side and in case of SSR fast render.

The other option is [Kadira Fast-render](https://github.com/kadirahq/fast-render), in such a case and quoting:

> Fast render runs the waitOn function (or one of the Fast Render API calls) on the server and gets the subscription data relavant to the page you are loading

Those are different options, and both work on Server side only. 

So the answer to your question is NO and I understand that both options do not work on client side using data already cached but only on Server side.

I think you need something like [GroundDB](https://github.com/GroundMeteor/db), we currently use it in conjunction with this plugin to get offline data using IndexedDB on browser.

Hope it helps.

**Comment by janat08** [comment]
Did you actually publish the update, because I can't see new package version?

**Comment by paranoico** [comment]
Not yet, it could probably be delayed to next week.

**Comment by janat08** [comment]
stilll not deployed?

**Comment by gazhayes** [comment]
FYI if anyone needs this for their project it's been resolved here: https://github.com/Blockrazor/subscache-C4

**Comment by gazhayes** [comment]
We have forked this repository [here](https://github.com/Blockrazor/subscache-C4) and used the C4 contribution protocol to allow the repository to be self-managing and also facilitate extremely fast merges of pull requests. 

The changes referenced here have been merged and the updated package is available on atmosphere as blockrazor:subscache-c4.

**Comment by paranoico** [comment]
Very good and thanks a lot @gazhayes 

To us it is better to Not update immediately atmosphere since we use this component on our biggest projects. So we rather prefer to use source code some weeks before updating.

**Comment by gazhayes** [comment]
No problem, similar situation for us just from a different angle (we like to live dangerously!). Whenever we make improvements on our repo I'll send a courtesy pull request back here to your repo in case you also want to integrate it :)

**Comment by paranoico** [comment]
Thanks again, very kind of you.

We currently are struggling to migrate our main apps to react-native, so we are facing some other problems regarding our offline implementation.

My best regards.

**Comment by paranoico** [comment]
Atmosphere package upgraded minutes ago.
