### ISSUE TITLE
@ready() is not a function

### ISSUE THREAD

**Issue by satyavh** [ccorcos/meteor-subs-cache#5]
I'm getting these errors and have no idea why. 

```
Uncaught TypeError: this.ready is not a function
SubsCache.SubsCache.subscribeFor.cachedSub.onReady @ subsCache.coffee:72
```

So I've been loggin this out, and in some cases @ doesn't refer to a subscription, but to something else. It could be related to Iron Router onWait, because I"m waiting for subscriptions like this:

```
    waitOn: ->
      [ 
        SubsCache.subscribe 'userDirectory',
        SubsCache.subscribe 'posts',
        SubsCache.subscribe, 'singlePost', @params.id
      ]   
```

so this works when
- I navigate from another route, but when loading this route directly I get this @ready() is not a function error. 
- I use Meteor.subscribe. As soon as I change to SubsCache I get this error

Any ideas?

**Comment by satyavh** [comment]
FYI,  I've changed to `meteorhacks:subs-manager` with exactly the same code and now it all works fine.

**Comment by ccorcos** [comment]
Hmm. You're talking about right here:

https://github.com/ccorcos/meteor-subs-cache/blob/master/src/subsCache.coffee#L72

Can you give me a full trace? Iron router may be binding the function elsewhere or something...
