### ISSUE TITLE
subscriptionId params are always passed

### ISSUE THREAD

**Issue by satyavh** [ccorcos/meteor-subs-cache#6]
this
`SubsCache.subscribe 'posts'`

gets passed to the publication like this:
`{ subscriptionId: '4FHxbDWHRdFufDi2e' }`

my publication handles different params
`Meteor.reactivePublish "posts", (orgId, limit, starredOnly, collectionId) -> ...`

but in this case I don't set any params for the subscription. Yet, subsCache adds params which are being passed.
`orgId { subscriptionId: '4FHxbDWHRdFufDi2e' }`

**Comment by ccorcos** [comment]
You need to do `SubsCache.subscribe 'posts', orgId, limit, starredOnly, collectionId` to pass the parameters to your publication...
