### ISSUE TITLE
Subscription timer not stopped when calling clearAll()

### ISSUE THREAD

**Issue by santiagopuentep** [ccorcos/meteor-subs-cache#60]
`clearAll()` does not clear the expiration timeout of the subscriptions.

**Comment by paranoico** [comment]
Are you using the last version on atmosphere or the master branch?

**Comment by santiagopuentep** [comment]
I was using the version on atmosphere.

**Comment by jankapunkt** [comment]
Created a PR, see #62 - I hope it fixes this issue.

**Comment by paranoico** [comment]
Atmosphere package has been updated also.

**Comment by paranoico** [comment]
Closing for now, if problem persist please reopen.
