### ISSUE TITLE
onReady callback isn't called when subscription is already active

### ISSUE THREAD

**Issue by BudgieInWA** [ccorcos/meteor-subs-cache#7]
When providing an onReady callback to `Meteor.subscribe`, it will always be called, even if an identical subscription is already active. `subsCache.subscribe` does not behave in this way; if a subscription with the same arguments already exists, the callback is ignored.

For example

```
var l = function() { console.log("onReady"); };
var sc = new SubsCache({
  expireAter: 5,
  cacheLimit: 10
});

Meteor.subscribe("mysub", l); // "onReady"
Meteor.subscribe("mysub", l); // "onReady"

sc.subscribe("mysub", l); // "onReady"
sc.subscribe("mysub", l); // nothing, never
```

**Comment by ccorcos** [comment]
OK. I think that's reasonable. We can fix this with one line of code. Simple call onReady right here:

https://github.com/ccorcos/meteor-subs-cache/blob/master/src/subsCache.coffee#L92

You want to implement it, see if it works, and submit a PR?

**Comment by BudgieInWA** [comment]
I'm working on it now. It's not completely straight forward because there are onStop (and deprecated onError) callbacks too.

**Comment by ccorcos** [comment]
I'm not sure why there shouldn't be just one line?

I don't think we need to call every onReady function that has ever been passed to subscribe -- only the most recent one that was passed this one time...

**Comment by trakkif** [comment]
hi, is this going to be fixed?  I've just spent 3-4 hours trying to work out why my code wasn't working, and finally worked out its because using subscache means my default (onReady) callback doesn't ever fire.  Seems this bug has been forgotten?  thanks

**Comment by ccorcos** [comment]
I see. Bummer man. I don't care to support the deprecated hooks, but if you want to submit a PR to fix the onReady call, then I'll merge it.

You can clone this repo into your /packages directory to develop with it locally.

**Comment by BudgieInWA** [comment]
#8 is still pending and fixes this. 

@ccorcos I'd love a final review.

@trakkif If you need a working copy ASAP, clone my fork into the `packages` dir and you're off.

**Comment by ccorcos** [comment]
ok should be good to go
