### ISSUE TITLE
When cacheLimit is hit, the data gets wiped away

### ISSUE THREAD

**Issue by rclai** [ccorcos/meteor-subs-cache#9]
```js
subsMgt = new SubsCache({
  expireAter: 5,  // minutes
  cacheLimit: 10
});

// Inside `autorun` inside `onCreated` callbacks
this.autorun(function () {
    var listId = FlowRouter.getParam('_id');
    if (listId) {
      self.listSub = subsMgt.subscribe('list', listId);
    }
  });

// Here's another
this.autorun(function () {
    if (Session.equals('listIsLoaded', true)) {
      var listItem = getListItem();
      if (listItem && listItem.someField) {
        self.listItemSub = subsMgt.subscribe('otherStuff', listIem.someField);
      }
    }
  });
```

If I change the `cacheLimit` to 1, the page will show the data and then the data will disappear because when I go to the list route, it will subscribe to the list, and find the last recently visited list item and go to it and subscribe to that, and once that happens, cache limit is hit and the data gets wiped for some odd reason.

Workaround right now is to set `cacheLimit` to `-1` and manually stopping previous subscriptions.

**Comment by ccorcos** [comment]
Hmm. So that seems like the intended functionality with a cacheLimit of 1. That means that the cache can only have one subscription at a time and previous subscriptions will be stopped. Perhaps what you intended was to have two separate caches, one for `list` and the other for `otherStuff`.

**Comment by rclai** [comment]
Oh I see that makes sense. So the way it's intended to be used is that one `SubsCache` needs to be instantiated per unique subscription?

**Comment by ccorcos** [comment]
Yeah. Just think of it as a really lightweight and simple caching mechanism. If it can only hold one, then it will boot the previous one. This is actually pretty convenient to be used this way sometimes. But if you want to cache 5 users and 5 posts, it better to have 2 caches of 5 rather than one with 10. Otherwise, you could end up with 10 users and 0 posts being caches...

**Comment by rclai** [comment]
Okay, thanks.
